In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
from typing import List

import os
import wandb
import nest_asyncio
import pandas as pd

nest_asyncio.apply()

while "freqtrade" not in os.listdir():
    os.chdir("..")
    
from freqtrade.nbtools.dataloader import load_dataset

PATH_MOUNT = Path.cwd().parent / "mount"
PATH_DATA = PATH_MOUNT / "data"
BINANCE = PATH_DATA / "binance"

PAIRS_HIGH_CAP = [
    "BTC/USDT","ETH/USDT","ADA/USDT","BNB/USDT","XRP/USDT","DOT/USDT","DOGE/USDT","ZEC/USDT","NANO/USDT","NEO/USDT",
    "UNI/USDT","BCH/USDT","LINK/USDT","LTC/USDT","MATIC/USDT","XLM/USDT","SOL/USDT","ETC/USDT","VET/USDT","THETA/USDT",
    "EOS/USDT","TRX/USDT","FIL/USDT","XMR/USDT","AAVE/USDT","MKR/USDT","ATOM/USDT","ALGO/USDT","KSM/USDT", "TFUEL/USDT",
    "LUNA/USDT","BTT/USDT","AVAX/USDT","COMP/USDT","DASH/USDT","DCR/USDT","EGLD/USDT","WAVES/USDT","YFI/USDT","XEM/USDT",
    "CHZ/USDT","SUSHI/USDT","HOT/USDT","ZIL/USDT","SNX/USDT","MANA/USDT","ENJ/USDT","HNT/USDT","BAT/USDT","NEAR/USDT",
    "QTUM/USDT","ONE/USDT","ONT/USDT","BNT/USDT","ZRX/USDT","FTM/USDT","OMG/USDT", "ICX/USDT","ANKR/USDT","RVN/USDT",
    "CRV/USDT", "FTT/USDT", 
]

In [2]:


        
train = TrainingConfiguration()
df_exp = load_dataset(DATASET, add_features, add_labels, TRAINVAL_START, TRAINVAL_END)

Pairs: ['AAVE_USDT-5m.json', 'ADA_USDT-5m.json', 'ALGO_USDT-5m.json', 'ANKR_USDT-5m.json', 'ATOM_USDT-5m.json', 'AVAX_USDT-5m.json', 'BAT_USDT-5m.json', 'BCH_USDT-5m.json', 'BNB_USDT-5m.json', 'BNT_USDT-5m.json', 'BTC_USDT-5m.json', 'BTT_USDT-5m.json', 'CHZ_USDT-5m.json', 'COMP_USDT-5m.json', 'CRV_USDT-5m.json', 'DASH_USDT-5m.json', 'DCR_USDT-5m.json', 'DOGE_USDT-5m.json', 'DOT_USDT-5m.json', 'EGLD_USDT-5m.json', 'ENJ_USDT-5m.json', 'EOS_USDT-5m.json', 'ETC_USDT-5m.json', 'ETH_USDT-5m.json', 'FIL_USDT-5m.json', 'FTM_USDT-5m.json', 'FTT_USDT-5m.json', 'HNT_USDT-5m.json', 'HOT_USDT-5m.json', 'ICX_USDT-5m.json', 'KSM_USDT-5m.json', 'LINK_USDT-5m.json', 'LTC_USDT-5m.json', 'LUNA_USDT-5m.json', 'MANA_USDT-5m.json', 'MATIC_USDT-5m.json', 'MKR_USDT-5m.json', 'NANO_USDT-5m.json', 'NEAR_USDT-5m.json', 'NEO_USDT-5m.json', 'OMG_USDT-5m.json', 'ONE_USDT-5m.json', 'ONT_USDT-5m.json', 'QTUM_USDT-5m.json', 'RVN_USDT-5m.json', 'SNX_USDT-5m.json', 'SOL_USDT-5m.json', 'SUSHI_USDT-5m.json', 'TFUEL_USDT-5m.json', 'THETA_USDT-5m.json', 'TRX_USDT-5m.json', 'UNI_USDT-5m.json', 'VET_USDT-5m.json', 'WAVES_USDT-5m.json', 'XEM_USDT-5m.json', 'XLM_USDT-5m.json', 'XMR_USDT-5m.json', 'XRP_USDT-5m.json', 'YFI_USDT-5m.json', 'ZEC_USDT-5m.json', 'ZIL_USDT-5m.json', 'ZRX_USDT-5m.json']

Loading: AAVE_USDT-5m.json
Loading: ADA_USDT-5m.json
Loading: ALGO_USDT-5m.json
Loading: ANKR_USDT-5m.json
Loading: ATOM_USDT-5m.json
Loading: AVAX_USDT-5m.json
Loading: BAT_USDT-5m.json
Loading: BCH_USDT-5m.json
Loading: BNB_USDT-5m.json
Loading: BNT_USDT-5m.json
Loading: BTC_USDT-5m.json
Loading: BTT_USDT-5m.json
Loading: CHZ_USDT-5m.json
Loading: COMP_USDT-5m.json
Loading: CRV_USDT-5m.json
Loading: DASH_USDT-5m.json
Loading: DCR_USDT-5m.json
Loading: DOGE_USDT-5m.json
Loading: DOT_USDT-5m.json
Loading: EGLD_USDT-5m.json
Loading: ENJ_USDT-5m.json
Loading: EOS_USDT-5m.json
Loading: ETC_USDT-5m.json
Loading: ETH_USDT-5m.json
Loading: FIL_USDT-5m.json
Loading: FTM_USDT-5m.json
Loading: FTT_USDT-5m.json
Loading: HNT_USDT-5m.json
Loading: HOT_USDT-5m.json
Loading: ICX_USDT-5m.json
Loading: KSM_USDT-5m.json
Loading: LINK_USDT-5m.json
Loading: LTC_USDT-5m.json
Loading: LUNA_USDT-5m.json
Loading: MANA_USDT-5m.json
Loading: MATIC_USDT-5m.json
Loading: MKR_USDT-5m.json
Loading: NANO_USDT-5m.json
Loading: NEAR_USDT-5m.json
Loading: NEO_USDT-5m.json
Loading: OMG_USDT-5m.json
Loading: ONE_USDT-5m.json
Loading: ONT_USDT-5m.json
Loading: QTUM_USDT-5m.json
Loading: RVN_USDT-5m.json
Loading: SNX_USDT-5m.json
Loading: SOL_USDT-5m.json
Loading: SUSHI_USDT-5m.json
Loading: TFUEL_USDT-5m.json
Loading: THETA_USDT-5m.json
Loading: TRX_USDT-5m.json
Loading: UNI_USDT-5m.json
Loading: VET_USDT-5m.json
Loading: WAVES_USDT-5m.json
Loading: XEM_USDT-5m.json
Loading: XLM_USDT-5m.json
Loading: XMR_USDT-5m.json
Loading: XRP_USDT-5m.json
Loading: YFI_USDT-5m.json
Loading: ZEC_USDT-5m.json
Loading: ZIL_USDT-5m.json
Loading: ZRX_USDT-5m.json
LOAD DATASET FINISHED.

In [25]:
print("Dataframe Rows:", len(df_exp))
df_exp.head()

Dataframe Rows: 1466973

,date,open,high,low,close,volume,pair,ml_smadiff_3,ml_maxdiff_3,ml_mindiff_3,...,ml_maxdiff_500,ml_mindiff_500,ml_std_500,ml_ma_500,ml_rsi_500,ml_bop,ml_volume_pctchange,ml_z_score_120,ml_target,ml_target_real
40336,2021-03-04 11:25:00,385.243988,385.500000,382.510010,383.493988,1298.712036,AAVE/USDT,1.987345,3.678009,0.000000,...,33.562012,-5.734985,8.631269,0.044950,50.101040,-0.585286,2.436455,1.632589,2.0,0.007288
40341,2021-03-04 11:50:00,385.908997,386.854004,385.816986,386.147003,160.425995,AAVE/USDT,0.263997,0.649994,0.000000,...,30.908997,-8.388000,8.697610,0.043788,50.266285,0.229511,1.005400,1.312327,2.0,0.006272
40342,2021-03-04 11:55:00,386.123993,386.596008,385.654999,386.002014,476.988007,AAVE/USDT,0.143992,0.286987,0.000000,...,31.053986,-8.243011,8.709859,0.043627,50.257057,-0.129625,1.973259,1.039620,2.0,0.014344
40343,2021-03-04 12:00:00,385.649994,388.500000,383.649994,384.178986,423.691986,AAVE/USDT,1.263682,1.968018,0.000000,...,32.877014,-6.419983,8.729833,0.043441,50.141098,-0.303300,-0.111735,0.812169,2.0,0.017705
40344,2021-03-04 12:05:00,384.170013,387.996002,383.920013,387.093994,310.644989,AAVE/USDT,-1.335663,0.000000,-2.915009,...,29.962006,-9.334991,8.741722,0.043254,50.324741,0.717367,-0.266814,0.739566,2.0,0.010266

In [26]:
# Make sure float datatypes are float32 
df_exp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1466973 entries, 40336 to 234809
Data columns (total 66 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   date                 1466973 non-null  datetime64[ns]
 1   open                 1466973 non-null  float32
 2   high                 1466973 non-null  float32
 3   low                  1466973 non-null  float32
 4   close                1466973 non-null  float32
 5   volume               1466973 non-null  float32
 6   pair                 1466973 non-null  object
 7   ml_smadiff_3         1466973 non-null  float32
 8   ml_maxdiff_3         1466973 non-null  float32
 9   ml_mindiff_3         1466973 non-null  float32
 10  ml_std_3             1466973 non-null  float32
 11  ml_ma_3              1466973 non-null  float32
 12  ml_rsi_3             1466973 non-null  float32
 13  ml_smadiff_5         1466973 non-null  float32
 14  ml_maxdiff_5         1466973 non-null  float32
 15  ml_mindiff_5         1466973 non-null  float32
 16  ml_std_5             1466973 non-null  float32
 17  ml_ma_5              1466973 non-null  float32
 18  ml_rsi_5             1466973 non-null  float32
 19  ml_smadiff_9         1466973 non-null  float32
 20  ml_maxdiff_9         1466973 non-null  float32
 21  ml_mindiff_9         1466973 non-null  float32
 22  ml_std_9             1466973 non-null  float32
 23  ml_ma_9              1466973 non-null  float32
 24  ml_rsi_9             1466973 non-null  float32
 25  ml_smadiff_15        1466973 non-null  float32
 26  ml_maxdiff_15        1466973 non-null  float32
 27  ml_mindiff_15        1466973 non-null  float32
 28  ml_std_15            1466973 non-null  float32
 29  ml_ma_15             1466973 non-null  float32
 30  ml_rsi_15            1466973 non-null  float32
 31  ml_smadiff_25        1466973 non-null  float32
 32  ml_maxdiff_25        1466973 non-null  float32
 33  ml_mindiff_25        1466973 non-null  float32
 34  ml_std_25            1466973 non-null  float32
 35  ml_ma_25             1466973 non-null  float32
 36  ml_rsi_25            1466973 non-null  float32
 37  ml_smadiff_50        1466973 non-null  float32
 38  ml_maxdiff_50        1466973 non-null  float32
 39  ml_mindiff_50        1466973 non-null  float32
 40  ml_std_50            1466973 non-null  float32
 41  ml_ma_50             1466973 non-null  float32
 42  ml_rsi_50            1466973 non-null  float32
 43  ml_smadiff_100       1466973 non-null  float32
 44  ml_maxdiff_100       1466973 non-null  float32
 45  ml_mindiff_100       1466973 non-null  float32
 46  ml_std_100           1466973 non-null  float32
 47  ml_ma_100            1466973 non-null  float32
 48  ml_rsi_100           1466973 non-null  float32
 49  ml_smadiff_200       1466973 non-null  float32
 50  ml_maxdiff_200       1466973 non-null  float32
 51  ml_mindiff_200       1466973 non-null  float32
 52  ml_std_200           1466973 non-null  float32
 53  ml_ma_200            1466973 non-null  float32
 54  ml_rsi_200           1466973 non-null  float32
 55  ml_smadiff_500       1466973 non-null  float32
 56  ml_maxdiff_500       1466973 non-null  float32
 57  ml_mindiff_500       1466973 non-null  float32
 58  ml_std_500           1466973 non-null  float32
 59  ml_ma_500            1466973 non-null  float32
 60  ml_rsi_500           1466973 non-null  float32
 61  ml_bop               1466973 non-null  float32
 62  ml_volume_pctchange  1466973 non-null  float32
 63  ml_z_score_120       1466973 non-null  float32
 64  ml_target            1466973 non-null  float32
 65  ml_target_real       1466973 non-null  float32
dtypes: datetime64[ns](1), float32(64), object(1)
memory usage: 391.7+ MB

In [27]:
display(df_exp.groupby(by=["ml_target"]).count()["date"])

ml_target
0.0    489585
1.0    490449
2.0    486939
Name: date, dtype: int64

In [ ]:
def training_pipeline(run):
    """ After done exploring and correcting dataset, call this function."""
    
    # TODO: Split num of data equally to number of classes (if classification)
    # TODO: Neural Network prediction as a feature for Catboost
    # TODO: Add `Reinforcement Learning` layer below
    # -> https://github.com/THINK989/Real-Time-Stock-Market-Prediction-using-Ensemble-DL-and-Rainbow-DQN

    from catboost import CatBoostClassifier
    from sklearn.model_selection import train_test_split
    import gc
    
    # Save memory
    global df_exp
    del df_exp
    gc.collect()
    
    df_all = load_dataset(DATASET, FEATURE_FUNCTION, LABEL_FUNCTION, TRAINVAL_START, TRAINVAL_END)
    df_all = df_all.sample(frac=1).reset_index(drop=True)
    
    col_use = [col for col in df_all.columns if col not in COLUMNS_NOT_USE]
    
    X = df_all[col_use]
    y = df_all["ml_target"]
    
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=1)